<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function RechercheReclamationUser($idUser)
    {
        $query = $this->getEntityManager()->createQuery("Select r FROM ReclamationBundle\Entity\Reclamation r WHERE r.idUser=:idUser")
            ->setParameter('idUser',$idUser);
        return $query->getResult();

    }
}
