produit_homepage:
    path:     /
    defaults: { _controller: ProduitBundle:Default:index }

produit_Afficher:
    path:     /admin/AfficherProduit
    defaults: { _controller: ProduitBundle:Produit:AfficheProduit }

produit_Supprimer:
    path:     /admin/deleteProduit/{id}
    defaults: { _controller: ProduitBundle:Produit:deleteProduit }


produit_Modifier:
    path:     /admin/ModifierProduit/{id}
    defaults: { _controller: ProduitBundle:Produit:ModifierProduit }

Promotion_Ajout:
    path:     /admin/ajouterPromotion
    defaults: { _controller: ProduitBundle:Promotion:AjoutPromotion }

Promotion_Affiche:
    path:     /admin/AfficherPromotion
    defaults: { _controller: ProduitBundle:Promotion:AffichePromotion }


Promotion_Delete:
    path:     /admin/DeletePromotion/{id}
    defaults: { _controller: ProduitBundle:Promotion:deletePromotion }

Promotion_Modifier:
    path:     /admin/ModifierPromotion/{id}
    defaults: { _controller: ProduitBundle:Promotion:ModifierPromotion }

Poromo_Front:
    path:     /Client/AfficherPromoFront
    defaults: { _controller: ProduitBundle:Promotion:AffichePromotionFront }

Produit_Front:
    path:     /Client/AfficherProduitFront
    defaults: { _controller: ProduitBundle:Produit:AfficheProduitFront }


