reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

panier:
    resource: "@PanierBundle/Resources/config/routing.yml"
    prefix:   /


produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /


stock:
    resource: "@StockBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications