<?php

namespace PanierBundle\Repository;

/**
 * HistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function RechercheHistorique($idUser)
    {
        $query = $this->getEntityManager()->createQuery("Select h FROM PanierBundle\Entity\Historique h WHERE h.idUtilisateur=:idUser")
            ->setParameter('idUser',$idUser);
        return $query->getResult();

    }
}
