<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function ProduitName($nom){
        $query = $this->getEntityManager()->createQuery("Select p FROM ProduitBundle\Entity\Produit p WHERE p.nom=:nom")
            ->setParameter('nom',$nom);
        return $query->getOneOrNullResult();
    }


}
